trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool: az-400

variables:
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    version: '3.1.x'  # Changed to 3.1 (LTS) instead of 3.0 (EOL)

- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/dotnetfoundation-website.csproj
    arguments: '-c $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/website'  # Fixed: / instead of \
    zipAfterPublish: True

- publish: $(Build.ArtifactStagingDirectory)/website  # Fixed: / instead of \
  displayName: Publish website artifact
  artifact: website